#!/bin/sh

StagedTsFiles=$(deno run --allow-env --allow-read --allow-run ./src/githooks/outputStagedTsFiles.ts)
echo $StagedTsFiles


if deno lint $StagedTsFiles; then
    echo yo
    # exit 0
else
    echo Fix linting
    exit 1
fi

exit 1